[tool.poetry]
name = "mathematics-artwork"
version = "0.0.1"
description = "The author's personal mathematical artworks."
authors = ["O957 <127630341+O957@users.noreply.github.com>"]
license = "Apache-2.0"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
pre-commit = "^3.7.0"


[tool.poetry.group.dev.dependencies]
networkx = "^3.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
